version: '3'

services:
  flask-backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - node-server

  node-server:
    build:
      context: ./node-server
    ports:
      - "3000:3000"
